# 应用名称
spring:
  application:
    name: demo-gateway
  cloud:
    sentinel:
      transport:
        dashboard: 121.4.127.248:8080
        port: 8012
#        clientIp: 139.155.8.239
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: demo-auth-route
          uri: lb://demo-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: demo-route
          uri: lb://demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

server:
  port: 8010

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8011
logging:
  config: classpath:log4j2-dev.xml
  level:
    cn.qaq.demo_gateway: info
