# 应用名称
spring:
  application:
    name: demo-gateway
  cloud:
    sentinel:
#      enabled: false
      transport:
        dashboard: 139.155.8.239:8080
        port: 8012
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: demo-auth-route
          uri: lb://demo_auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: demo-route
          uri: lb://demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

server:
  port: 8010

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8011