apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  namespace: demos
spec:
  replicas: 2
  selector:
    matchLabels:
      project: demos
      app: spring-gateway
  template:
    metadata:
      labels:
        project: demos
        app: spring-gateway
    spec:
      imagePullSecrets:
        - name: registry-pull-secert
      containers:
        - name: spring-gateway
          image: hippowdon/demo-gateway-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              containerPort: 8010
          env:
            - name: JAVA_OPTS
              value: "-Xms256M -Xmx256M"

